using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HNSys.Model
{
    class OverRoll
    {
        public string CellectTime { get; set; }
        public float Parameter1 { get; set; }

        public float Parameter2 { get; set; }
        public float Parameter3 { get; set; }
        public float Parameter4 { get; set; }
        public float Parameter5 { get; set; }
        public float Parameter6 { get; set; }
        public float Parameter7 { get; set; }
        public float Parameter8 { get; set; }
        public float Parameter9 { get; set; }
        public float Parameter10 { get; set; }
        public float Parameter11 { get; set; }
        public float Parameter12 { get; set; }
        public float Parameter13 { get; set; }
        public float Parameter14 { get; set; }
        public float Parameter15 { get; set; }
        public float Parameter16 { get; set; }
        public float Parameter17 { get; set; }
        public float Parameter18 { get; set; }
        public float Parameter19 { get; set; }
        public float Parameter20 { get; set; }
        public float Parameter21 { get; set; }
        public float Parameter22 { get; set; }
        public float Parameter23 { get; set; }
        public float Parameter24 { get; set; }
        public float Parameter25 { get; set; }
        public float Parameter26 { get; set; }
        public float Parameter27 { get; set; }
        public float Parameter28 { get; set; }
        public float Parameter29 { get; set; }
        public float Parameter30 { get; set; }
        public float Parameter31 { get; set; }
        public float Parameter32 { get; set; }
        public float Parameter33 { get; set; }
        public float Parameter34 { get; set; }
        public float Parameter35 { get; set; }
        public float Parameter36 { get; set; }
        public float Parameter37 { get; set; }
        public float Parameter38 { get; set; }
        public float Parameter39 { get; set; }
        public float Parameter40 { get; set; }
        public float Parameter41 { get; set; }
        public float Parameter42 { get; set; }
        public float Parameter43 { get; set; }
        public float Parameter44 { get; set; }
        public float Parameter45 { get; set; }
        public float Parameter46 { get; set; }
        public float Parameter47 { get; set; }
        public float Parameter48 { get; set; }
        public float Parameter49 { get; set; }
        public float Parameter50 { get; set; }
        public float Parameter51 { get; set; }
        public float Parameter52 { get; set; }
        public float Parameter53 { get; set; }
        public float Parameter54 { get; set; }
        public float Parameter55 { get; set; }
        public float Parameter56 { get; set; }
        public float Parameter57 { get; set; }
        public float Parameter58 { get; set; }
        public float Parameter59 { get; set; }
        public float Parameter60 { get; set; }
        public float Parameter61 { get; set; }
        public float Parameter62 { get; set; }
        public float Parameter63 { get; set; }
        public float Parameter64 { get; set; }
        public float Parameter65 { get; set; }
        public float Parameter66 { get; set; }
        public float Parameter67 { get; set; }
        public float Parameter68 { get; set; }
        public float Parameter69 { get; set; }
        public float Parameter70 { get; set; }
        public float Parameter71 { get; set; }
        public float Parameter72 { get; set; }
        public float Parameter73 { get; set; }
        public float Parameter74 { get; set; }
        public float Parameter75 { get; set; }
        public float Parameter76 { get; set; }
        public float Parameter77 { get; set; }
        public float Parameter78 { get; set; }
        public float Parameter79 { get; set; }
        public float Parameter80 { get; set; }
        public float Parameter81 { get; set; }
        public float Parameter82 { get; set; }
        public float Parameter83 { get; set; }
        public float Parameter84 { get; set; }
        public float Parameter85 { get; set; }
        public float Parameter86 { get; set; }
        public float Parameter87 { get; set; }
        public float Parameter88 { get; set; }
        public float Parameter89 { get; set; }
        public float Parameter90 { get; set; }
        public float Parameter91 { get; set; }
        public float Parameter92 { get; set; }
        public float Parameter93 { get; set; }
        public float Parameter94 { get; set; }
        public float Parameter95 { get; set; }
        public float Parameter96 { get; set; }
        public float Parameter97 { get; set; }
        public float Parameter98 { get; set; }
        public float Parameter99 { get; set; }
        public float Parameter100 { get; set; }
        public float Parameter101 { get; set; }
        public float Parameter102 { get; set; }
        public float Parameter103 { get; set; }
        public float Parameter104 { get; set; }
        public float Parameter105 { get; set; }
        public float Parameter106 { get; set; }
        public float Parameter107 { get; set; }
        public float Parameter108 { get; set; }
        public float Parameter109 { get; set; }
        public float Parameter110 { get; set; }
        public float Parameter111 { get; set; }
        public float Parameter112 { get; set; }
        public float Parameter113 { get; set; }
        public float Parameter114 { get; set; }
        public float Parameter115 { get; set; }
        public float Parameter116 { get; set; }
        public float Parameter117 { get; set; }
        public float Parameter118 { get; set; }
        public float Parameter119 { get; set; }
        public float Parameter120 { get; set; }
        public float Parameter121 { get; set; }
        public float Parameter122 { get; set; }
        public float Parameter123 { get; set; }
        public float Parameter124 { get; set; }
        public float Parameter125 { get; set; }
        public float Parameter126 { get; set; }
        public float Parameter127 { get; set; }
        public float Parameter128 { get; set; }
        public float Parameter129 { get; set; }
        public float Parameter130 { get; set; }
        public float Parameter131 { get; set; }
        public float Parameter132 { get; set; }
        public float Parameter133 { get; set; }
        public float Parameter134 { get; set; }
        public float Parameter135 { get; set; }
        public float Parameter136 { get; set; }
        public float Parameter137 { get; set; }
        public float Parameter138 { get; set; }
        public float Parameter139 { get; set; }
        public float Parameter140 { get; set; }
        public float Parameter141 { get; set; }
        public float Parameter142 { get; set; }
        public float Parameter143 { get; set; }
        public float Parameter144 { get; set; }
        public float Parameter145 { get; set; }
        public float Parameter146 { get; set; }
        public float Parameter147 { get; set; }
        public float Parameter148 { get; set; }
        public float Parameter149 { get; set; }
        public float Parameter150 { get; set; }
        public float Parameter151 { get; set; }
        public float Parameter152 { get; set; }
        public float Parameter153 { get; set; }
        public float Parameter154 { get; set; }
        public float Parameter155 { get; set; }
        public float Parameter156 { get; set; }
        public float Parameter157 { get; set; }
        public float Parameter158 { get; set; }
        public float Parameter159 { get; set; }
        public float Parameter160 { get; set; }
        public float Parameter161 { get; set; }
        public float Parameter162 { get; set; }
        public float Parameter163 { get; set; }
        public float Parameter164 { get; set; }
        public float Parameter165 { get; set; }
        public float Parameter166 { get; set; }
        public float Parameter167 { get; set; }
        public float Parameter168 { get; set; }

    }
}
